<?xml version="1.0"?>
<?xml-model href="http://download.ros.org/schema/package_format3.xsd" schematypens="http://www.w3.org/2001/XMLSchema"?>
<package format="3">
  <name>pbtm_ros2</name>
  <version>0.0.0</version>
  <description>PX4 B-spline Trajectory Manager</description>
  <maintainer email="tslywh@nus.edu.sg">wayne</maintainer>
  <license>Apache-2.0</license>

  <buildtool_depend>ament_cmake</buildtool_depend>
 
  <build_depend>rclcpp</build_depend>
  <build_depend>trajectory_msgs</build_depend>
  <build_depend>pcl_ros</build_depend>

  <build_export_depend>rclcpp</build_export_depend>
  <build_export_depend>trajectory_msgs</build_export_depend>
  <build_export_depend>pcl_ros</build_export_depend>

  <exec_depend>rclcpp</exec_depend>
  <exec_depend>trajectory_msgs</exec_depend>
  <exec_depend>pcl_ros</exec_depend>

  <test_depend>ament_lint_auto</test_depend>
  <test_depend>ament_lint_common</test_depend>

  <export>
    <build_type>ament_cmake</build_type>
  </export>
</package>
